# Generated by Django 5.1.1 on 2024-09-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('player_choice', models.CharField(max_length=10)),
                ('computer_choice', models.CharField(max_length=10)),
                ('winner', models.CharField(max_length=10)),
                ('round_number', models.PositiveIntegerField()),
            ],
        ),
    ]
