# Generated by Django 5.1.1 on 2024-10-23 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamesapp', '0003_alter_gameresult_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameresult',
            name='player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gamesapp.player'),
        ),
    ]
